name: _
publish_to: none
environment:
  sdk: ^3.7.0
workspace:
  - app
  - packages/components
  - packages/domain/model
  - packages/domain/repository
  - packages/data/adapter
  - packages/data/local
  - packages/data/api

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true