name: sota_flutter_template
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  component:
    path: ../packages/presentation/component
  page:
    path: ../packages/presentation/page
  domain:
    path: ../packages/domain
  data:
    path: ../packages/data

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true 