name: model
description: Domain models package
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.4
  very_good_analysis: ^7.0.0 