name: domain
description: Unified domain package
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
resolution: workspace

dependencies:
  freezed_annotation: ^3.0.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.4
  lints: ^5.1.1
  very_good_analysis: ^7.0.0 