name: feature
description: Feature modules package
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  components:
    path: ../components
  model:
    path: ../domain/model
  repository:
    path: ../domain/repository
  adapter:
    path: ../data/adapter
  local:
    path: ../data/local
  api:
    path: ../data/api

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0 